SELECT a.AUTHOR_ID, AUTHOR_NAME, CATEGORY, (SUM(SALES * PRICE)) AS TOTAL_SALES
FROM BOOK b
    JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
    JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY a.AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;