SELECT ri.FOOD_TYPE, ri.REST_ID, ri.REST_NAME, ri.FAVORITES
FROM REST_INFO ri
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES 
     FROM REST_INFO
     GROUP BY FOOD_TYPE) AS mf
ON ri.FOOD_TYPE = mf.FOOD_TYPE
AND ri.FAVORITES = mf.FAVORITES
ORDER BY FOOD_TYPE DESC;