SELECT rh.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY rh JOIN CAR_RENTAL_COMPANY_CAR cc ON rh.CAR_ID = cc.CAR_ID
WHERE CAR_TYPE = '세단' AND MONTH(START_DATE) = 10
GROUP BY rh.CAR_ID
ORDER BY rh.CAR_ID DESC;