SELECT ID, FISH_NAME, f.LENGTH
FROM FISH_INFO f
JOIN FISH_NAME_INFO fn ON f.FISH_TYPE = fn.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
      FROM FISH_INFO 
      GROUP BY FISH_TYPE) AS max_fish 
ON f.FISH_TYPE = max_fish.FISH_TYPE AND f.LENGTH = max_fish.LENGTH
ORDER BY ID;